// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package beaconspotproto

import (
	context "context"

	health "github.com/begmaroman/beaconspot/proto/health"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BeaconSpotServiceClient is the client API for BeaconSpotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BeaconSpotServiceClient interface {
	Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*health.HealthResponse, error)
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	// Attester
	GetAttestation(ctx context.Context, in *GetAttestationRequest, opts ...grpc.CallOption) (*GetAttestationResponse, error)
	ProposeAttestation(ctx context.Context, in *ProposeAttestationRequest, opts ...grpc.CallOption) (*ProposeAttestationResponse, error)
}

type beaconSpotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBeaconSpotServiceClient(cc grpc.ClientConnInterface) BeaconSpotServiceClient {
	return &beaconSpotServiceClient{cc}
}

func (c *beaconSpotServiceClient) Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*health.HealthResponse, error) {
	out := new(health.HealthResponse)
	err := c.cc.Invoke(ctx, "/grpcapiproto.BeaconSpotService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSpotServiceClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpcapiproto.BeaconSpotService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSpotServiceClient) GetAttestation(ctx context.Context, in *GetAttestationRequest, opts ...grpc.CallOption) (*GetAttestationResponse, error) {
	out := new(GetAttestationResponse)
	err := c.cc.Invoke(ctx, "/grpcapiproto.BeaconSpotService/GetAttestation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSpotServiceClient) ProposeAttestation(ctx context.Context, in *ProposeAttestationRequest, opts ...grpc.CallOption) (*ProposeAttestationResponse, error) {
	out := new(ProposeAttestationResponse)
	err := c.cc.Invoke(ctx, "/grpcapiproto.BeaconSpotService/ProposeAttestation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeaconSpotServiceServer is the server API for BeaconSpotService service.
// All implementations must embed UnimplementedBeaconSpotServiceServer
// for forward compatibility
type BeaconSpotServiceServer interface {
	Health(context.Context, *empty.Empty) (*health.HealthResponse, error)
	Ping(context.Context, *empty.Empty) (*empty.Empty, error)
	// Attester
	GetAttestation(context.Context, *GetAttestationRequest) (*GetAttestationResponse, error)
	ProposeAttestation(context.Context, *ProposeAttestationRequest) (*ProposeAttestationResponse, error)
	mustEmbedUnimplementedBeaconSpotServiceServer()
}

// UnimplementedBeaconSpotServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBeaconSpotServiceServer struct {
}

func (UnimplementedBeaconSpotServiceServer) Health(context.Context, *empty.Empty) (*health.HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedBeaconSpotServiceServer) Ping(context.Context, *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBeaconSpotServiceServer) GetAttestation(context.Context, *GetAttestationRequest) (*GetAttestationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttestation not implemented")
}
func (UnimplementedBeaconSpotServiceServer) ProposeAttestation(context.Context, *ProposeAttestationRequest) (*ProposeAttestationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeAttestation not implemented")
}
func (UnimplementedBeaconSpotServiceServer) mustEmbedUnimplementedBeaconSpotServiceServer() {}

// UnsafeBeaconSpotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BeaconSpotServiceServer will
// result in compilation errors.
type UnsafeBeaconSpotServiceServer interface {
	mustEmbedUnimplementedBeaconSpotServiceServer()
}

func RegisterBeaconSpotServiceServer(s grpc.ServiceRegistrar, srv BeaconSpotServiceServer) {
	s.RegisterService(&BeaconSpotService_ServiceDesc, srv)
}

func _BeaconSpotService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSpotServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapiproto.BeaconSpotService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSpotServiceServer).Health(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSpotService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSpotServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapiproto.BeaconSpotService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSpotServiceServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSpotService_GetAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSpotServiceServer).GetAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapiproto.BeaconSpotService/GetAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSpotServiceServer).GetAttestation(ctx, req.(*GetAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSpotService_ProposeAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSpotServiceServer).ProposeAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapiproto.BeaconSpotService/ProposeAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSpotServiceServer).ProposeAttestation(ctx, req.(*ProposeAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BeaconSpotService_ServiceDesc is the grpc.ServiceDesc for BeaconSpotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BeaconSpotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapiproto.BeaconSpotService",
	HandlerType: (*BeaconSpotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _BeaconSpotService_Health_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _BeaconSpotService_Ping_Handler,
		},
		{
			MethodName: "GetAttestation",
			Handler:    _BeaconSpotService_GetAttestation_Handler,
		},
		{
			MethodName: "ProposeAttestation",
			Handler:    _BeaconSpotService_ProposeAttestation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/begmaroman/beaconspot/proto/beaconspot/beaconspot.proto",
}
